name: warehouse_scanner
description: Ein Flutter-Projekt, das Barcodes im Lager scannen, Fotos aufnehmen und speichern kann.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  gallery_saver: ^2.3.2
  cupertino_icons: ^1.0.2  
  flutter_barcode_sdk: ^2.2.4
  flutter_barcode_scanner: ^2.0.0
  flutter_plugin_android_lifecycle: ^2.0.1
  image_picker: ^1.0.0
  shared_preferences: ^2.1.1
  path_provider: ^2.0.9
  path: ^1.8.3
  camera: ^0.10.5+9
  camera_windows: 
    git:
      url: https://github.com/yushulx/flutter_camera_windows.git
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  flutter_exif_rotation: ^0.5.1
  camera_platform_interface: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon_lager.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/app_icon_lager.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/app_icon_lager.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/app_icon_lager.png"

flutter:
  uses-material-design: true
